### ISSUE TITLE
Use gtk-3

### ISSUE THREAD

**Issue by nomeata** [def-/ghc-vis#12]
Hi,

as a way to work around [the issue with GHC-7.10](https://github.com/gtk2hs/gtk2hs/issues/105), it might be prudent to upgrade to gtk3.

I gave it a shot and it compiles, but when I run it from ghci, I get
```
(<interactive>:21898): GLib-GObject-WARNING **: cannot register existing type 'GtkWidget'

(<interactive>:21898): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(<interactive>:21898): GLib-GObject-WARNING **: cannot register existing type 'GtkBuildable'

(<interactive>:21898): GLib-GObject-CRITICAL **: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed

(<interactive>:21898): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(<interactive>:21898): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(<interactive>:21898): Gtk-CRITICAL **: IA__gtk_widget_show_all: assertion 'GTK_IS_WIDGET (widget)' failed
```

Using it in ghc yields:

```
(nonghci-test:22194): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
```

I’ll keep digging.

**Comment by nomeata** [comment]
Ok, I must also adjust `xdot` to also use `gtk3`, then the window at least comes up

**Comment by nomeata** [comment]
It seems to be working, see branches `gtk3` in my forks of `xdot` and `ghc-vis`. Dennis, care to have a look?

Anyone else: Testing is appreciated!

**Comment by def-** [comment]
Sounds like switching to GTK3 is reasonable.

**Comment by def-** [comment]
Thanks, merged it, fixed a small thing. Looks fine to me now.

**Comment by nomeata** [comment]
That is because of polymorphism, it seems. If you give it a type signature, it seems to work as intended (which is somewhat expected).

**Comment by def-** [comment]
Right, forgot about that. So I guess I can make a release with the GTK3 version if no one finds further problems.

**Comment by nomeata** [comment]
I don’t think there are many people testing the repository version, so yes, a release would make sense.

**Comment by def-** [comment]
Released. Now I'll have to figure out new installation instructions for all these weird platforms.

**Comment by FranklinChen** [comment]
I built on Mac OS X 10.11.3 (El Capitan) with the Homebrew GHC 7.10.3 and Stack, but when I try to use in `stack repl`, I get

```
(ghc:15943): GLib-GIO-CRITICAL **: g_file_monitor_emit_event: assertion 'G_IS_FILE_MONITOR (monitor)' failed
```

**Comment by def-** [comment]
Ah great, someone is trying! Not sure where your bug comes from yet.

I'm currently getting it to work on Windows, ran into a few problems as well:
- https://github.com/gtk2hs/gtk2hs/issues/139
- https://github.com/gtk2hs/gtk2hs/pull/152

**Comment by RyanGlScott** [comment]
@def- https://github.com/gtk2hs/gtk2hs/issues/139 and https://github.com/gtk2hs/gtk2hs/pull/152 should [both](https://github.com/gtk2hs/gtk2hs/pull/140) [be](https://github.com/gtk2hs/gtk2hs/pull/113) [fixed](https://github.com/Alexpux/MINGW-packages/pull/1062) now. Can you try building `gtk2hs` from [source](https://github.com/gtk2hs/gtk2hs) and seeing if it works?

**Comment by def-** [comment]
I got it working and wrote down how here: http://felsin9.de/nnis/ghc-vis/installing-windows/

I guess I'll simplify it once the new gtk related cabal packages are out.

**Comment by RyanGlScott** [comment]
Great! This kind of thing (minus the `--ghc-options=--"force"` bit, since that should no longer be needed) would be great to write down in the `gtk2hs` wiki for future curious Windows users.
