### ISSUE TITLE
error, called at src/GHC/Disassembler.hs:238:18 

### ISSUE THREAD

**Issue by varosi** [def-/ghc-vis#17]
```
let a = "11"
> :view a
> ghc: Unknown opcode 0
CallStack (from HasCallStack):
  error, called at src/GHC/Disassembler.hs:238:18 in ghc-heap-view-0.5.9-I35KGkMGAdhFBgqAev4Hpi:GHC.Disassembler
```

CentOS 7, GHC 8.0.2 (LTS 8.8) from master branch of ghc-vis

**Comment by nomeata** [comment]
@varosi, can you reproduce it with the latest version of `ghc-heap-view`?

**Comment by nomeata** [comment]
Hmm, I can reproduce it :-(

**Comment by varosi** [comment]
Yes, it's still reproducable in latest master aa2f2f3a99e5d336b412e45bd0610c52b91261d4

**Comment by varosi** [comment]
Great! It's working, but I have to include latest:
https://github.com/nomeata/ghc-heap-view.git

**Comment by varosi** [comment]
And this one: https://github.com/def-/ghc-vis/pull/18
