### ISSUE TITLE
Unknown command ':vis'

### ISSUE THREAD

**Issue by rikvdkleij** [def-/ghc-vis#5]
I have installed ghc-vis succesfully in sandbox with:
 `cabal install ghc-vis --disable-library-profiling` 

When I start `cabal-repl` and execute:
`:set -package ghc-vis`
Output:
Loading package array-0.5.0.0 ... linking ... done.
Loading package deepseq-1.3.0.2 ... linking ... done.
Loading package bytestring-0.10.4.0 ... linking ... done.
Loading package transformers-0.3.0.0 ... linking ... done.
Loading package mtl-2.1.3.1 ... linking ... done.
Loading package text-1.2.0.4 ... linking ... done.
Loading package utf8-string-1 ... linking ... done.
Loading package cairo-0.13.1.0 ... linking ... done.
Loading package containers-0.5.5.1 ... linking ... done.
Loading package fgl-5.5.1.0 ... linking ... done.
Loading package binary-0.7.1.0 ... linking ... done.
Loading package filepath-1.3.0.2 ... linking ... done.
Loading package old-locale-1.0.0.6 ... linking ... done.
Loading package time-1.4.2 ... linking ... done.
Loading package unix-2.7.0.1 ... linking ... done.
Loading package directory-1.2.1.0 ... linking ... done.
Loading package pretty-1.1.1.1 ... linking ... done.
Loading package process-1.2.0.0 ... linking ... done.
Loading package Cabal-1.18.1.5 ... linking ... done.
Loading package bin-package-db-0.0.0.0 ... linking ... done.
Loading package hoopl-3.10.0.1 ... linking ... done.
Loading package hpc-0.6.0.1 ... linking ... done.
Loading package template-haskell ... linking ... done.
Loading package ghc-7.8.4 ... linking ... done.
Loading package ghc-heap-view-0.5.3 ... linking ... done.
Loading package colour-2.3.3 ... linking ... done.
Loading package dlist-0.7.1.1 ... linking ... done.
Loading package polyparse-1.9 ... linking ... done.
Loading package stm-2.4.4 ... linking ... done.
Loading package transformers-compat-0.4.0.4 ... linking ... done.
Loading package exceptions-0.8.0.2 ... linking ... done.
Loading package temporary-1.2.0.3 ... linking ... done.
Loading package wl-pprint-text-1.1.0.3 ... linking ... done.
Loading package graphviz-2999.17.0.2 ... linking ... done.
Loading package glib-0.13.1.0 ... linking ... done.
Loading package gio-0.13.0.4 ... linking ... done.
Loading package pango-0.13.0.5 ... linking ... done.
Loading package gtk-0.13.4 ... linking ... done.
Loading package svgcairo-0.13.0.2 ... linking ... done.
Loading package xdot-0.2.4.6 ... linking ... done.
Loading package ghc-vis-0.7.2.7 ... linking ... done.

When I execute:
`:vis`
Output:
`unknown command ':vis'
use :? for help.`

Any idea what is going wrong?

Ubuntu and GHC 7.8.4

**Comment by def-** [comment]
I guess cabal is still removing my custom instructions. You'll need to add this to your `.ghci` file:

```
:script /home/USER/.cabal/share/ghc-vis-0.7.2.7/ghci
```

**Comment by rikvdkleij** [comment]
Yes, that helps. Thanks.
