### ISSUE TITLE
Update for base 4.8

### ISSUE THREAD

**Issue by treeowl** [def-/ghc-vis#7]
Currently, the base version is restricted to `<4.8`. Since 4.8 can reasonably be expected to come out real soon now, it's probably time to see what needs to be changed to make it work with that. Many packages experience build failures related to the `Applicative => Monad` change. I don't know if this is one of them.

**Comment by FranklinChen** [comment]
This change will also need https://github.com/nomeata/ghc-heap-view/issues/4 in order to work, and possibly other lib version changes as well.

**Comment by FranklinChen** [comment]
I got it to build on GHC 7.10.1 but have not fully tested it, and also it depends on patching graphviz trivially for 7.10.1 (but nobody has updated it on Hackage) http://hub.darcs.net/ivanm/graphviz/issue/5

Here's my fork: https://github.com/FranklinChen/ghc-vis/tree/update-for-710

**Comment by def-** [comment]
I tried the same, but I'd like to wait until the dependencies are fixed, but the graphviz maintainer doesn't respond to my emails.

**Comment by FranklinChen** [comment]
Yes, it has been useless for me to try to contact the graphviz maintainer. I don't know whom to appeal to to essentially take over graphviz and upload a new version to Hackage.

**Comment by treeowl** [comment]
@FranklinChen, that goes via Hackage stewards. Email haskell-cafe to get their attention. Use a subject like "Taking over graphviz".

**Comment by FranklinChen** [comment]
It appears a new version of Graphviz has been released, with migration of the code repo to GitHub: https://github.com/ivan-m/graphviz

I'm going to try again to get ghc-vis working.

**Comment by simonmichael** [comment]
Any luck ?

**Comment by FranklinChen** [comment]
Something was wrong with the gtk stuff on Mac OS where I am, and I will try again to see if that's been fixed.

**Comment by FranklinChen** [comment]
Got `ghc-vis` building and displaying properly on my Mac (only catch being remembering to Cabal install with a special flag for `gtk` on Mac OS https://github.com/gtk2hs/gtk2hs/issues/112). Waiting for Travis build to verify a successful build on multiple GHC versions in Linux before submitting a pull request.
