### ISSUE TITLE
"Command not found: dot"

### ISSUE THREAD

**Issue by jhafranco** [def-/ghc-vis#8]
I am not able to visualize Haskell expressions using ghc-vis on Ubuntu. A simplified GHCi session transcript follows:

$ ghci
GHCi, version 7.6.3: http://www.haskell.org/ghc/  :? for help
...
λ: :vis
Loading package array-0.4.0.1 ... linking ... done.
...
Loading package xdot-0.2.4.7 ... linking ... done.
Loading package ghc-vis-0.7.2.7 ... linking ... done.
(visualization window appears)
λ: let x = head [1 .. 5]
λ: :view x
\<interactive\>: Command not found: dot
λ:

**Comment by def-** [comment]
You need to install graphviz with a `sudo apt-get install graphviz`.

**Comment by jhafranco** [comment]
Now it's ok. Thx for the (very) quick response!

**Comment by def-** [comment]
Great to hear, you're welcome!
